### ISSUE TITLE
Gimmighoul catch/flee rate?

### ISSUE THREAD

**Issue by svivian** [PokeMiners/game_masters#3]
Do you have these mixed up? The gamemaster shows:

    "baseCaptureRate": 0.03,
    "baseFleeRate": 0.5,

However the catch rate is certainly not 3% in the game. It pretty much always has a green circle so I'd say it's 50% and the flee rate is likely 3% (though I haven't had one flee yet due to the high catch rate).

**Comment by marty0678** [comment]
We don't manually create the Game Master, it's decoded directly from Niantic's network messages, so that's what Niantic is setting that to.

The circle colour can be overridden from the server if the server's BCR doesn't match the GM's, which is most likely what is happening here (they used to do that with Rockets).

**Comment by lewymd** [comment]
As a additional note we have reports of once the coin bag buff expires gimmighoul become very hard to catch so it would seem there is something happening server side while that buff is active.
